using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/*Sun class  is defines behaviour of "Sun " which is the currency in the game.
 we have defined two types of motion for  sun depending on wheather it is generated by the spawner or generated using sunflower*/
public class Sun : MonoBehaviour
{
    private float fspeed = 1f;
    private float timer = 0f;
    private float lifetime = 11f;
    [SerializeField]
    [HideInInspector]
    private bool sunflowerSun = false;

    // Update is called once per frame
    void Update()
    {
        if (!sunflowerSun)
        {
            transform.Translate(Vector2.down * fspeed * Time.deltaTime);                //sun drops downwards on backyard if it is generated by spwanner function
        }

        timer += Time.deltaTime;
        if (timer >= lifetime)
        {
            Destroy(gameObject);
        }
    }

    public void flowerSun(bool value)                                                  //assigns value  if sun is generated from sunflower
    {
        sunflowerSun = value;
    }
}